name: "Build Sphinx Site"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - "build-action" # So I can iterate on a separate branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # We need Python 3.10 for set union operations
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: directly build sphinx
        run: |
          pip install -r requirements.txt
          sphinx-build -D todo_include_todos=0 docs ./docs/_build/html/
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
